openapi: 3.0.0
info:
  version: 1.0.0
  title: Contacts API
servers:
  - url: http://localhost:3000
paths:
  /contacts:
    get:
      tags:
        - Contacts
      summary: Get list of contacts
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successfully found contacts!
          content:
            application/json:
              schema:
                type: object
  /contacts/{id}:
    get:
      tags:
        - Contacts
      summary: Get contact by id
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successfully found contact!
          content:
            application/json:
              schema:
                type: object
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
